/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description Append-only trail. There is deliberately no delete endpoint.
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Human sign-in. The response carries ``server_time`` so the client can
         *     establish its clock offset before anything is timed.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/machine/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol Machine
         * @description One-time workstation enrolment, performed by an administrator.
         *
         *     Returns the machine secret exactly once; it is stored hashed.
         */
        post: operations["enrolMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/machine/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Machine Token
         * @description Exchanges a machine credential for a short-lived token carrying
         *     ``subject_type=machine``. Such a token may only reach heartbeat and event
         *     endpoints.
         */
        post: operations["machineToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["getCurrentPrincipal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/computers/{machine_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Heartbeat
         * @description Liveness ping from a workstation. Machine subjects only.
         *
         *     High volume by design - 60 machines in a lab. Held in Redis rather than
         *     written as a row per beat.
         */
        post: operations["postHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exams
         * @description Backs the assessments table and the dashboard.
         */
        get: operations["listExams"];
        put?: never;
        /**
         * Create Exam
         * @description Creates the exam as a DRAFT.
         */
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam
         * @description Faculty-facing detail, including answer keys.
         *
         *     Never reachable by a STUDENT subject; candidates read their paper through
         *     ``GET /sessions/{id}`` instead.
         */
        get: operations["getExam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Exam
         * @description Rejected with 409 unless the exam is still DRAFT.
         */
        patch: operations["updateExam"];
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Exam
         * @description Requires a reason, which is written to the audit trail as CRITICAL.
         */
        post: operations["cancelExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Exam
         * @description Closes the exam early. Enters ENDING and begins the sweep.
         */
        post: operations["endExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Monitor
         * @description Server-computed aggregates plus rows.
         *
         *     Also the documented fallback when the websocket is unavailable: the same
         *     reducer consumes this and a live frame, so losing the socket degrades the
         *     refresh rate rather than correctness.
         */
        get: operations["getExamMonitor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Results
         * @description Ranked results. Scores are omitted while unpublished.
         */
        get: operations["getExamResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/results/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Exam Results
         * @description Releases scores to candidates by setting ``published_at``.
         */
        post: operations["publishExamResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule Exam
         * @description DRAFT to SCHEDULED, then seats the roster to reach READY.
         *
         *     Validates the roster against lab capacity inside the same transaction. The
         *     frontend performs this check too, but only as UX - a candidate can edit the
         *     client, so this is where it actually holds.
         */
        post: operations["scheduleExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exam Sessions
         * @description The readiness roster before start, and the monitor table during.
         */
        get: operations["listExamSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Exam
         * @description Stamps the authoritative window and releases waiting candidates.
         *
         *     Idempotent: a retry with the same idempotency key returns the existing
         *     window rather than shifting it, and candidates already answering are left
         *     untouched.
         */
        post: operations["startExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Labs */
        get: operations["listLabs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/{lab_id}/computers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lab Computers
         * @description Workstations and their derived liveness.
         *
         *     No candidate is attached here: seating belongs to the session, because a
         *     lab hosts a different cohort every hour.
         */
        get: operations["listLabComputers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Exams
         * @description Assessments the authenticated candidate is enrolled in.
         */
        get: operations["listMyExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Paper
         * @description The paper as ordered for this candidate. Carries no answer keys.
         */
        get: operations["getSessionPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/answers/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Answer
         * @description Idempotent upsert of one answer.
         *
         *     ``client_seq`` lets a stale write that arrives late after a reconnect be
         *     discarded without relying on either clock.
         */
        put: operations["saveAnswer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check In
         * @description Enters the waiting room and materializes this candidate's paper.
         *
         *     The question and option ordering is drawn **once, here**, and persisted on
         *     the session. Recomputing it per request would reshuffle the paper on
         *     reconnect and leave every saved answer pointing at the wrong question.
         */
        post: operations["checkInSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Detail
         * @description Invigilator drill-down: identity, machine, timings, and event timeline.
         *
         *     Faculty scope - this is the monitor's detail drawer, not a candidate view.
         */
        get: operations["getSessionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Session Event
         * @description Invigilation signal from the lab client. Machine subjects only.
         *
         *     Accepted and recorded as evidence; a focus loss raises a warning count but
         *     is never treated on its own as proof of misconduct.
         */
        post: operations["reportSessionEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/flags/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle Flag
         * @description Toggles the review flag for one question.
         */
        put: operations["toggleFlag"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session State
         * @description Reconnect recovery.
         *
         *     Returns the server's view of every saved answer, so a client that missed
         *     acknowledgements during a network drop can tell what actually landed
         *     instead of guessing.
         */
        get: operations["getSessionState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Session
         * @description Final submission.
         *
         *     Idempotent: a repeat call returns the original receipt rather than
         *     recording a second submission.
         */
        post: operations["submitSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["listStudents"];
        put?: never;
        /** Create Student */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Student */
        patch: operations["updateStudent"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEntry */
        ActivityEntry: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Detail */
            detail?: string | null;
            /** Event */
            event: string;
            /** Severity */
            severity: string;
        };
        /**
         * AuditCategory
         * @enum {string}
         */
        AuditCategory: "AUTH" | "EXAM" | "SESSION" | "CONNECTION" | "SYSTEM";
        /**
         * AuditEventOut
         * @description One append-only trail entry.
         *
         *     Two timestamps, deliberately. ``occurred_at`` is what the reporting client
         *     claimed; ``recorded_at`` is when the server accepted it. Keeping both means
         *     clock skew - or a deliberately altered client clock - is visible in the
         *     data instead of silently corrupting the ordering of the timeline.
         */
        AuditEventOut: {
            /** Actorlabel */
            actorLabel: string;
            actorType: components["schemas"]["SubjectType"];
            category: components["schemas"]["AuditCategory"];
            /** Detail */
            detail: string;
            event: components["schemas"]["AuditEventType"];
            /** Examid */
            examId?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Machineid */
            machineId?: string | null;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Recordedat
             * Format: date-time
             */
            recordedAt: string;
            /** Sessionid */
            sessionId?: string | null;
            severity: components["schemas"]["AuditSeverity"];
            /** Studentid */
            studentId?: string | null;
        };
        /**
         * AuditEventType
         * @description Append-only event vocabulary.
         *
         *     Deliberately includes the invigilation signals the lab client will report
         *     once it exists. ``FOCUS_LOST`` is recorded as evidence and contributes to a
         *     warning count; it is never treated as proof of anything on its own.
         * @enum {string}
         */
        AuditEventType: "LOGIN" | "LOGOUT" | "EXAM_CREATED" | "EXAM_SCHEDULED" | "EXAM_STARTED" | "EXAM_ENDED" | "EXAM_CANCELLED" | "SESSION_CHECKED_IN" | "CONNECTION_LOST" | "CONNECTION_RESTORED" | "FOCUS_LOST" | "FOCUS_RESTORED" | "EXAM_CLIENT_CLOSED" | "ANSWER_SAVED" | "SUBMISSION" | "AUTO_SUBMISSION" | "SESSION_TERMINATED" | "RESULTS_PUBLISHED";
        /**
         * AuditSeverity
         * @enum {string}
         */
        AuditSeverity: "INFO" | "WARNING" | "CRITICAL";
        /**
         * CheckInRequest
         * @description Sent by the candidate's client on entering the waiting room.
         *
         *     The machine identifier is reported by the lab client, not typed by the
         *     candidate - binding a student to a workstation is the client's job.
         */
        CheckInRequest: {
            /** Machineid */
            machineId?: string | null;
        };
        /**
         * ClientFrame
         * @description Base envelope for lab-client to server frames.
         */
        ClientFrame: {
            event: components["schemas"]["RealtimeEvent"];
            /** Machineid */
            machineId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Sessionid
             * @default null
             */
            sessionId: string | null;
        };
        /**
         * ComputerOut
         * @description A workstation.
         *
         *     Deliberately has no ``student_id``. Seating is a fact about a candidate
         *     sitting a particular exam, recorded on the session - a lab hosts a
         *     different cohort every hour, so a permanent binding cannot hold.
         */
        ComputerOut: {
            connection: components["schemas"]["ConnectionState"];
            /** Enrolledat */
            enrolledAt?: string | null;
            /** Hostname */
            hostname?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Lastheartbeatat */
            lastHeartbeatAt?: string | null;
            /** Machineid */
            machineId: string;
            /** Position */
            position: number;
        };
        /**
         * ConnectionState
         * @description Derived liveness, never stored.
         *
         *     Computed from ``now - last_heartbeat_at`` against two thresholds, so it is
         *     always current rather than as-of the last write.
         * @enum {string}
         */
        ConnectionState: "online" | "warning" | "offline";
        /**
         * ErrorDetail
         * @description Uniform error body.
         *
         *     ``code`` is stable and machine-readable; ``message`` is for humans and may
         *     change. Transition failures carry the states involved so the client can say
         *     something useful rather than 'something went wrong'.
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Currentstate */
            currentState?: string | null;
            /** Message */
            message: string;
            /** Requestedstate */
            requestedState?: string | null;
        };
        /** ExamCancelRequest */
        ExamCancelRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * ExamConfig
         * @description Delivery rules applied per candidate session.
         *
         *     ``questions_per_student`` is why the question bank exists: drawing a subset
         *     requires a pool larger than the paper. Zero means "use the whole paper".
         *
         *     Randomization is materialized into the session at check-in and persisted -
         *     never recomputed per request, or a reconnect would reshuffle the paper and
         *     every saved answer would point at the wrong question.
         */
        ExamConfig: {
            /**
             * Allownavigation
             * @default true
             */
            allowNavigation: boolean;
            /**
             * Autosubmitonexpiry
             * @default true
             */
            autoSubmitOnExpiry: boolean;
            /**
             * Questionsperstudent
             * @default 0
             */
            questionsPerStudent: number;
            /**
             * Randomizeoptions
             * @default false
             */
            randomizeOptions: boolean;
            /**
             * Randomizequestions
             * @default false
             */
            randomizeQuestions: boolean;
        };
        /** ExamCreate */
        ExamCreate: {
            /** Code */
            code: string;
            config?: components["schemas"]["ExamConfig"];
            /** Course */
            course: string;
            /** Department */
            department: string;
            /** Description */
            description?: string | null;
            /** Durationminutes */
            durationMinutes: number;
            /** Instructions */
            instructions?: string[];
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Questionids */
            questionIds?: string[];
            /**
             * Scheduledat
             * Format: date-time
             */
            scheduledAt: string;
            /** Studentids */
            studentIds?: string[];
            /** Title */
            title: string;
        };
        /**
         * ExamDetail
         * @description Faculty-facing detail. Carries the answer key - never returned to a
         *     STUDENT subject.
         */
        ExamDetail: {
            /** Code */
            code: string;
            config: components["schemas"]["ExamConfig"];
            /** Course */
            course: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Createdby
             * Format: uuid
             */
            createdBy: string;
            /** Department */
            department: string;
            /** Description */
            description?: string | null;
            /** Durationminutes */
            durationMinutes: number;
            /** Endsat */
            endsAt?: string | null;
            /** Enrolledcount */
            enrolledCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instructions */
            instructions?: string[];
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Labname */
            labName: string;
            /** Questioncount */
            questionCount: number;
            /** Questions */
            questions?: components["schemas"]["QuestionOut"][];
            /**
             * Scheduledat
             * Format: date-time
             */
            scheduledAt: string;
            /** Startsat */
            startsAt?: string | null;
            status: components["schemas"]["ExamStatus"];
            /** Title */
            title: string;
            /** Totalmarks */
            totalMarks: number;
        };
        /**
         * ExamEndingFrame
         * @description Sent when the deadline is reached and the sweep begins.
         *
         *     Candidate writes are already refused by this point; the frame exists so the
         *     UI can say so rather than failing a save silently.
         */
        ExamEndingFrame: {
            /**
             * Endsat
             * Format: date-time
             */
            endsAt: string;
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
        };
        /**
         * ExamStartRequest
         * @description Start is idempotent, so a retried request must not shift the window.
         *
         *     ``idempotency_key`` lets the server recognise a retry of the *same* attempt
         *     rather than a deliberate restart.
         */
        ExamStartRequest: {
            /** Idempotencykey */
            idempotencyKey?: string | null;
        };
        /** ExamStartedFrame */
        ExamStartedFrame: {
            /**
             * Endsat
             * Format: date-time
             */
            endsAt: string;
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
        };
        /**
         * ExamStatus
         * @description Exam lifecycle.
         *
         *     ``READY`` exists because seating the roster is a real transition with
         *     observable consequences - faculty review candidate readiness in that state,
         *     before anyone is released into the paper.
         *
         *     ``ENDING`` is the deadline sweep window: the clock has run out and the
         *     server is auto-submitting stragglers, but the exam is not yet closed.
         *     Candidate writes are refused from the moment this state is entered.
         * @enum {string}
         */
        ExamStatus: "DRAFT" | "SCHEDULED" | "READY" | "LIVE" | "ENDING" | "COMPLETED" | "CANCELLED";
        /**
         * ExamSummary
         * @description List-row shape. Deliberately excludes questions - an assessments table
         *     of 200 exams must not carry every paper with it.
         */
        ExamSummary: {
            /** Code */
            code: string;
            /** Course */
            course: string;
            /** Department */
            department: string;
            /** Durationminutes */
            durationMinutes: number;
            /** Endsat */
            endsAt?: string | null;
            /** Enrolledcount */
            enrolledCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Labname */
            labName: string;
            /** Questioncount */
            questionCount: number;
            /**
             * Scheduledat
             * Format: date-time
             */
            scheduledAt: string;
            /** Startsat */
            startsAt?: string | null;
            status: components["schemas"]["ExamStatus"];
            /** Title */
            title: string;
            /** Totalmarks */
            totalMarks: number;
        };
        /**
         * ExamUpdate
         * @description Accepted only while the exam is DRAFT. Every field optional.
         */
        ExamUpdate: {
            config?: components["schemas"]["ExamConfig"] | null;
            /** Course */
            course?: string | null;
            /** Department */
            department?: string | null;
            /** Description */
            description?: string | null;
            /** Durationminutes */
            durationMinutes?: number | null;
            /** Instructions */
            instructions?: string[] | null;
            /** Labid */
            labId?: string | null;
            /** Questionids */
            questionIds?: string[] | null;
            /** Scheduledat */
            scheduledAt?: string | null;
            /** Studentids */
            studentIds?: string[] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * ExamWindow
         * @description Returned by start. This is the authoritative exam clock.
         */
        ExamWindow: {
            /**
             * Endsat
             * Format: date-time
             */
            endsAt: string;
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Releasedsessioncount */
            releasedSessionCount: number;
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
            status: components["schemas"]["ExamStatus"];
        };
        /**
         * FocusFrame
         * @description Focus lost or restored, reported by the lab client.
         */
        FocusFrame: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            event: components["schemas"]["RealtimeEvent"];
            /** Machineid */
            machineId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Sessionid
             * @default null
             */
            sessionId: string | null;
        };
        /**
         * ForceSubmitFrame
         * @description Instructs a candidate client to close the paper immediately.
         *
         *     Advisory only: the server has already stopped accepting that session's
         *     writes. A client that ignores this frame gains nothing.
         */
        ForceSubmitFrame: {
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Reason */
            reason: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeartbeatFrame
         * @description Liveness ping. High volume - held in Redis, never a row per beat.
         */
        HeartbeatFrame: {
            event: components["schemas"]["RealtimeEvent"];
            /** Machineid */
            machineId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Sessionid
             * @default null
             */
            sessionId: string | null;
        };
        /**
         * HeartbeatRequest
         * @description Posted by the lab client on an interval.
         *
         *     ``occurred_at`` is what the client believes; the server records its own
         *     arrival time separately, so a skewed or manipulated client clock is visible
         *     in the data rather than trusted.
         */
        HeartbeatRequest: {
            /** Machineid */
            machineId: string;
            /** Occurredat */
            occurredAt?: string | null;
            /** Sessionid */
            sessionId?: string | null;
        };
        /** LabOut */
        LabOut: {
            /** Building */
            building: string;
            /** Capacity */
            capacity: number;
            /** Computercount */
            computerCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invigilatorid */
            invigilatorId?: string | null;
            /** Invigilatorname */
            invigilatorName?: string | null;
            /** Name */
            name: string;
            /** Onlinecount */
            onlineCount: number;
            status: components["schemas"]["LabStatus"];
        };
        /**
         * LabStatus
         * @enum {string}
         */
        LabStatus: "READY" | "OCCUPIED" | "MAINTENANCE";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MachineCredential */
        MachineCredential: {
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Machineid */
            machineId: string;
            /** Secret */
            secret: string;
        };
        /**
         * MachineEnrolRequest
         * @description One-time enrolment, performed once per workstation by an administrator.
         *
         *     A workstation is not a user: it cannot own an exam, sit in a roster, or
         *     reset a password. Modelling it as a user row would mean every query
         *     touching users has to remember to exclude machines.
         */
        MachineEnrolRequest: {
            /** Enrolmenttoken */
            enrolmentToken: string;
            /** Hostname */
            hostname?: string | null;
            /** Machineid */
            machineId: string;
        };
        /** MachineToken */
        MachineToken: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /**
             * Labid
             * Format: uuid
             */
            labId: string;
            /** Machineid */
            machineId: string;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
        };
        /** MachineTokenRequest */
        MachineTokenRequest: {
            /** Machineid */
            machineId: string;
            /** Secret */
            secret: string;
        };
        /** MonitorSnapshot */
        MonitorSnapshot: {
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Rows */
            rows: components["schemas"]["SessionRow"][];
            /** Seq */
            seq: number;
            summary: components["schemas"]["MonitorSummary"];
        };
        /**
         * MonitorSummary
         * @description Server-computed aggregates.
         *
         *     Computed server-side rather than reduced in the browser because the monitor
         *     must stay correct when a lab has 200 sessions and the client is only
         *     holding a page of them.
         */
        MonitorSummary: {
            /** Active */
            active: number;
            /** Disconnected */
            disconnected: number;
            /** Enrolled */
            enrolled: number;
            /** Online */
            online: number;
            /** Submitted */
            submitted: number;
            /** Warnings */
            warnings: number;
        };
        /** MultipleAnswer */
        MultipleAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "multiple";
            /** Options */
            options?: number[];
        };
        /**
         * OptionOut
         * @description Faculty-facing option. Carries the answer key.
         */
        OptionOut: {
            /** Body */
            body: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Iscorrect */
            isCorrect: boolean;
            /** Position */
            position: number;
        };
        /** Page[AuditEventOut] */
        Page_AuditEventOut_: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[ExamSummary] */
        Page_ExamSummary_: {
            /** Items */
            items: components["schemas"]["ExamSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StudentOut] */
        Page_StudentOut_: {
            /** Items */
            items: components["schemas"]["StudentOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * Principal
         * @description Whoever is making the current request.
         *
         *     ``subject_type`` is what lets one dependency guard both humans and
         *     machines: heartbeat and event endpoints accept a machine subject, and
         *     nothing else does.
         */
        Principal: {
            role?: components["schemas"]["Role"] | null;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            /** Subjectid */
            subjectId: string;
            subjectType: components["schemas"]["SubjectType"];
        };
        /** PublishResultsRequest */
        PublishResultsRequest: {
            /** Published */
            published: boolean;
        };
        /**
         * QuestionOut
         * @description Faculty-facing question. Carries the answer key.
         *
         *     Returned by ``GET /exams/{id}`` and the question-bank endpoints, all of
         *     which require an ADMIN or FACULTY subject.
         */
        QuestionOut: {
            /** Course */
            course?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Marks */
            marks: number;
            /** Options */
            options?: components["schemas"]["OptionOut"][];
            /** Prompt */
            prompt: string;
            type: components["schemas"]["QuestionType"];
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "mcq" | "multiple" | "text";
        /**
         * RealtimeEvent
         * @description WebSocket frame types. Server-sent unless noted.
         * @enum {string}
         */
        RealtimeEvent: "EXAM_STARTED" | "EXAM_ENDING" | "EXAM_ENDED" | "SESSION_STATE_CHANGED" | "STUDENT_CONNECTED" | "STUDENT_DISCONNECTED" | "MACHINE_STATUS_CHANGED" | "WARNING" | "SUBMISSION" | "FORCE_SUBMIT" | "TERMINATED" | "ANSWER_ACK" | "HEARTBEAT" | "FOCUS_LOST" | "FOCUS_RESTORED" | "CLIENT_CLOSED";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * ResultRow
         * @description One ranked result.
         *
         *     ``score`` is null while results are unpublished. The frontend's
         *     ``mockResultMode`` switch was standing in for exactly this: grading and
         *     publication are separate events, and a score exists before a candidate is
         *     allowed to see it.
         */
        ResultRow: {
            /** Maxscore */
            maxScore: number;
            mode: components["schemas"]["SubmitMode"];
            /** Percentage */
            percentage?: number | null;
            /** Rank */
            rank: number;
            /** Registrationno */
            registrationNo: string;
            /** Score */
            score?: number | null;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /** Studentname */
            studentName: string;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Timetakenseconds */
            timeTakenSeconds?: number | null;
        };
        /** ResultStats */
        ResultStats: {
            /** Averagepercentage */
            averagePercentage?: number | null;
            /** Graded */
            graded: number;
            /** Highestpercentage */
            highestPercentage?: number | null;
            /** Submitted */
            submitted: number;
        };
        /** ResultsPage */
        ResultsPage: {
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /**
             * Published
             * @description False means scores are withheld; rows omit score and percentage.
             */
            published: boolean;
            /** Publishedat */
            publishedAt?: string | null;
            /** Rows */
            rows?: components["schemas"]["ResultRow"][];
            stats: components["schemas"]["ResultStats"];
        };
        /**
         * Role
         * @description Who a human principal is. Machines are not users - a lab workstation
         *     authenticates with its own credential and carries ``subject_type=machine``,
         *     so it never appears in a roster or owns an exam.
         * @enum {string}
         */
        Role: "ADMIN" | "FACULTY" | "STUDENT";
        /** SaveAnswerRequest */
        SaveAnswerRequest: {
            /**
             * Clientseq
             * @default 0
             */
            clientSeq: number;
            /** Value */
            value: components["schemas"]["SingleAnswer"] | components["schemas"]["MultipleAnswer"] | components["schemas"]["TextAnswer"];
        };
        /** SaveAnswerResponse */
        SaveAnswerResponse: {
            /**
             * Accepted
             * @description False when a newer write already won; the client should refetch state.
             */
            accepted: boolean;
            /**
             * Questionid
             * Format: uuid
             */
            questionId: string;
            /**
             * Savedat
             * Format: date-time
             */
            savedAt: string;
        };
        /**
         * ServerFrame
         * @description Base envelope for everything the server pushes.
         */
        ServerFrame: {
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
        };
        /**
         * SessionDetail
         * @description Drill-down for one candidate, including their event timeline.
         */
        SessionDetail: {
            /** Activity */
            activity?: components["schemas"]["ActivityEntry"][];
            /**
             * Answeredcount
             * @default 0
             */
            answeredCount: number;
            /** Checkedinat */
            checkedInAt?: string | null;
            connection: components["schemas"]["ConnectionState"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastheartbeatat */
            lastHeartbeatAt?: string | null;
            /** Machineid */
            machineId?: string | null;
            /** Registrationno */
            registrationNo: string;
            /** Startedat */
            startedAt?: string | null;
            status: components["schemas"]["SessionStatus"];
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /** Studentname */
            studentName: string;
            /** Submittedat */
            submittedAt?: string | null;
            /**
             * Warningcount
             * @default 0
             */
            warningCount: number;
        };
        /**
         * SessionEventRequest
         * @description Invigilation signal reported by the lab client.
         *
         *     A focus loss is recorded as evidence and raises a warning count. It is never
         *     treated, on its own, as proof of misconduct - faculty decide what a pattern
         *     means.
         */
        SessionEventRequest: {
            /** Detail */
            detail?: string | null;
            /** Event */
            event: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
        };
        /**
         * SessionPaper
         * @description Everything the candidate's exam screen needs, and nothing more.
         *
         *     Questions are :class:`StudentQuestionOut`, which has no answer-key field at
         *     all. Ordering is this candidate's persisted shuffle.
         */
        SessionPaper: {
            config: components["schemas"]["ExamConfig"];
            /** Endsat */
            endsAt?: string | null;
            /** Examcode */
            examCode: string;
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Examtitle */
            examTitle: string;
            /** Instructions */
            instructions?: string[];
            /** Questions */
            questions?: components["schemas"]["StudentQuestionOut"][];
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionRow
         * @description One row of the live monitor and of the pre-start readiness roster.
         *
         *     Note the two independent axes: ``status`` is lifecycle, ``connection`` is
         *     liveness derived from ``last_heartbeat_at``. A row reading
         *     ``ACTIVE`` + ``offline`` is meaningful and common - it is a candidate who
         *     was answering when their machine dropped.
         */
        SessionRow: {
            /**
             * Answeredcount
             * @default 0
             */
            answeredCount: number;
            /** Checkedinat */
            checkedInAt?: string | null;
            connection: components["schemas"]["ConnectionState"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastheartbeatat */
            lastHeartbeatAt?: string | null;
            /** Machineid */
            machineId?: string | null;
            /** Registrationno */
            registrationNo: string;
            /** Startedat */
            startedAt?: string | null;
            status: components["schemas"]["SessionStatus"];
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /** Studentname */
            studentName: string;
            /** Submittedat */
            submittedAt?: string | null;
            /**
             * Warningcount
             * @default 0
             */
            warningCount: number;
        };
        /**
         * SessionState
         * @description Reconnect recovery payload.
         *
         *     After a network drop the client asks for this and reconciles: it holds the
         *     server's view of every saved answer, so a client that missed acknowledgements
         *     can tell what actually landed.
         */
        SessionState: {
            /** Answers */
            answers?: {
                [key: string]: components["schemas"]["SingleAnswer"] | components["schemas"]["MultipleAnswer"] | components["schemas"]["TextAnswer"];
            };
            /** Endsat */
            endsAt?: string | null;
            /** Flagged */
            flagged?: string[];
            /** Serverseq */
            serverSeq: number;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionStateFrame
         * @description Sent to the monitor whenever a candidate's row changes.
         */
        SessionStateFrame: {
            /** Answeredcount */
            answeredCount: number;
            connection: components["schemas"]["ConnectionState"];
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /**
             * @description Recomputed aggregates, so the monitor never re-reduces the full roster.
             * @default null
             */
            summary: components["schemas"]["MonitorSummary"] | null;
            /** Warningcount */
            warningCount: number;
        };
        /**
         * SessionStatus
         * @description Per-candidate lifecycle.
         *
         *     Note what is absent: there is no ``DISCONNECTED`` member. Liveness is a
         *     separate axis (:class:`ConnectionState`) derived from the heartbeat, so a
         *     candidate can be correctly described as "ACTIVE but offline for 40s".
         *     Folding the two together would lose what the candidate was doing when the
         *     network dropped, which is exactly what an invigilator needs to know.
         * @enum {string}
         */
        SessionStatus: "NOT_STARTED" | "WAITING" | "READY" | "ACTIVE" | "SUBMITTED" | "AUTO_SUBMITTED" | "TERMINATED";
        /** SingleAnswer */
        SingleAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "single";
            /**
             * Option
             * @description Index into the options as ordered for this candidate.
             */
            option: number;
        };
        /** StudentCreate */
        StudentCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /** Program */
            program: string;
            /** Registrationno */
            registrationNo: string;
            /** Section */
            section: string;
            /** Semester */
            semester: number;
        };
        /**
         * StudentOptionOut
         * @description Candidate-facing option.
         *
         *     No ``is_correct``. The field does not exist on this model, so no serializer
         *     setting, response_model override, or future refactor can leak it.
         *
         *     ``position`` is this candidate's shuffled position, not the authored one.
         */
        StudentOptionOut: {
            /** Body */
            body: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
        };
        /** StudentOut */
        StudentOut: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Program */
            program: string;
            /** Registrationno */
            registrationNo: string;
            /** Section */
            section: string;
            /** Semester */
            semester: number;
            status: components["schemas"]["StudentStatus"];
        };
        /**
         * StudentQuestionOut
         * @description Candidate-facing question.
         *
         *     Ordering reflects the per-session shuffle materialized at check-in, so the
         *     paper is stable across reconnects. Marks are shown because candidates are
         *     told what each question is worth; nothing here reveals the answer.
         */
        StudentQuestionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Marks */
            marks: number;
            /** Options */
            options?: components["schemas"]["StudentOptionOut"][];
            /**
             * Position
             * @description Position in this candidate's paper, not the authored order.
             */
            position: number;
            /** Prompt */
            prompt: string;
            type: components["schemas"]["QuestionType"];
        };
        /**
         * StudentStatus
         * @enum {string}
         */
        StudentStatus: "ACTIVE" | "BLOCKED";
        /** StudentUpdate */
        StudentUpdate: {
            /** Email */
            email?: string | null;
            /** Fullname */
            fullName?: string | null;
            /** Program */
            program?: string | null;
            /** Section */
            section?: string | null;
            /** Semester */
            semester?: number | null;
            status?: components["schemas"]["StudentStatus"] | null;
        };
        /**
         * SubjectType
         * @description What kind of principal a token represents.
         * @enum {string}
         */
        SubjectType: "user" | "machine";
        /**
         * SubmissionReceipt
         * @description Returned by submit, and re-returned verbatim on a repeat submit.
         */
        SubmissionReceipt: {
            /** Answeredcount */
            answeredCount: number;
            /** Flaggedcount */
            flaggedCount: number;
            mode: components["schemas"]["SubmitMode"];
            /** Questioncount */
            questionCount: number;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /**
             * Submissionid
             * Format: uuid
             */
            submissionId: string;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
        };
        /**
         * SubmitMode
         * @enum {string}
         */
        SubmitMode: "MANUAL" | "AUTO" | "TERMINATED";
        /** SubmitRequest */
        SubmitRequest: {
            /** Idempotencykey */
            idempotencyKey?: string | null;
        };
        /** TextAnswer */
        TextAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Refreshtoken */
            refreshToken: string;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Registrationno */
            registrationNo?: string | null;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WarningFrame
         * @description An invigilation signal worth surfacing.
         *
         *     Evidence for a human to judge, not an accusation the system makes.
         */
        WarningFrame: {
            event: components["schemas"]["RealtimeEvent"];
            /**
             * Examid
             * Format: uuid
             */
            examId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Reason */
            reason: string;
            /** Seq */
            seq: number;
            /**
             * Servertime
             * Format: date-time
             */
            serverTime: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAuditEvents: {
        parameters: {
            query?: {
                examId?: string | null;
                studentId?: string | null;
                severity?: components["schemas"]["AuditSeverity"] | null;
                category?: components["schemas"]["AuditCategory"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enrolMachine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MachineEnrolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineCredential"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    machineToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MachineTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCurrentPrincipal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    postHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listExams: {
        parameters: {
            query?: {
                status?: components["schemas"]["ExamStatus"] | null;
                labId?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExamSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
            /** @description The exam is not in a state that permits this transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSummary"];
                };
            };
            /** @description The exam is not in a state that permits this transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamWindow"];
                };
            };
            /** @description The exam is not in a state that permits this transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getExamMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getExamResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publishExamResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduleExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
            /** @description The exam is not in a state that permits this transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listExamSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamWindow"];
                };
            };
            /** @description The exam is not in a state that permits this transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listLabs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOut"][];
                };
            };
        };
    };
    listLabComputers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lab_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMyExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSummary"][];
                };
            };
        };
    };
    getSessionPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPaper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saveAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAnswerResponse"];
                };
            };
            /** @description The exam is not LIVE or the session is not ACTIVE, so writes are refused. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkInSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPaper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSessionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reportSessionEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggleFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAnswerResponse"];
                };
            };
            /** @description The exam is not LIVE or the session is not ACTIVE, so writes are refused. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSessionState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionReceipt"];
                };
            };
            /** @description The exam is not LIVE or the session is not ACTIVE, so writes are refused. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listStudents: {
        parameters: {
            query?: {
                /** @description Matches name or registration number. */
                search?: string | null;
                section?: string | null;
                semester?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StudentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
