"""lab enrolment token

Revision ID: c416f7f80b9f
Revises: 78d79d3dcaa4
Create Date: 2026-09-09 14:23:43.476482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c416f7f80b9f'
down_revision: Union[str, Sequence[str], None] = '78d79d3dcaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('enrolment_token_hash', sa.String(length=255), nullable=True))
    op.add_column('labs', sa.Column('enrolment_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'enrolment_token_expires_at')
    op.drop_column('labs', 'enrolment_token_hash')
    # ### end Alembic commands ###
