"""marks for written answers

Revision ID: 8637c50b979b
Revises: c416f7f80b9f
Create Date: 2026-09-09 14:35:29.355991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8637c50b979b'
down_revision: Union[str, Sequence[str], None] = 'c416f7f80b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('awarded_marks', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('answers', sa.Column('marked_by', sa.Uuid(), nullable=True))
    op.add_column('answers', sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_answers_marked_by_users'), 'answers', 'users', ['marked_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_answers_marked_by_users'), 'answers', type_='foreignkey')
    op.drop_column('answers', 'marked_at')
    op.drop_column('answers', 'marked_by')
    op.drop_column('answers', 'awarded_marks')
    # ### end Alembic commands ###
