"""pending marking count

Revision ID: d62b94614d17
Revises: 8637c50b979b
Create Date: 2026-09-09 14:36:13.056610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62b94614d17'
down_revision: Union[str, Sequence[str], None] = '8637c50b979b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the column can be added to a table that already has
    # rows: existing results were graded before written answers could be
    # marked, so none of them are waiting on anybody.
    op.add_column(
        'results',
        sa.Column('pending_marking', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'pending_marking')
    # ### end Alembic commands ###
